GET http://127.0.0.1:8000/products/ HTTP/1.1

###
POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjE0ODY4LCJpYXQiOjE3NDUyMTQ1NjgsImp0aSI6IjQ3OGE0OTFkMjg2NjQ0OTlhZmIzOTI4YjJiYjRjZGQyIiwidXNlcl9pZCI6Mn0.qJnJf8rWcJGwSiXSJlhdi15HZtzoRPmf9FMjrguS_dw

{
    "name" : "Laptop",
    "price" : 1000.00,
    "stock" : 5,
    "description" : "ASUS"
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "rohit",
    "password" : "rohit"
}

###
GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjE1NjkzLCJpYXQiOjE3NDUyMTUzOTMsImp0aSI6IjJkMDU1YTYwNDdjMzQxYjViOGIyNzRjMGM1NzI4NjAyIiwidXNlcl9pZCI6MX0.Oe1ObOR-gSHkmNH0iTWcMhgwWBorIpNhF3xMEc-nsJw

###
POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTMwMzE0MiwiaWF0IjoxNzQ1MjE2NzQyLCJqdGkiOiJiM2ZlZjdkMjdiNjg0MTNlYTUxZWZmOWZlYTQzZmQwNiIsInVzZXJfaWQiOjF9.IQaW9yqgOLwPvCtbo8fTPvvQVxbUcfPchYu9iGcu2ak"
}